const ENV_CONSTANTS = {
  JWT: {
    ACCESS_SECRET: 'JWT_ACCESS_SECRET',
    REFRESH_SECRET: 'JWT_REFRESH_SECRET',
    ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRY',
    REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRY',
  },

  MINIO: {
    ENDPOINT: 'MINIO_ENDPOINT',
    PORT: 'MINIO_PORT',
    USE_SSL: 'MINIO_USE_SSL',
    ACCESS_KEY: 'MINIO_ACCESS_KEY',
    SECRET_KEY: 'MINIO_SECRET_KEY',
    BUCKET: 'MINIO_BUCKET',
  },
};

export default ENV_CONSTANTS;
