const ENV_CONSTANTS = {
  JWT: {
    ACCESS_SECRET: 'JWT_ACCESS_SECRET',
    REFRESH_SECRET: 'JWT_REFRESH_SECRET',
    ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRY',
    REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRY',
  },
};

export default ENV_CONSTANTS;
